-- 코드를 입력하세요
SELECT AU.AUTHOR_ID,AU.AUTHOR_NAME,BK.CATEGORY,SUM(BK.PRICE*SA.SALES) AS TOTAL_SALES
FROM BOOK BK LEFT JOIN AUTHOR AU ON BK.AUTHOR_ID=AU.AUTHOR_ID
LEFT JOIN BOOK_SALES SA ON BK.BOOK_ID=SA.BOOK_ID
WHERE SA.SALES_DATE LIKE "2022-01%"
GROUP BY AU.AUTHOR_ID,AU.AUTHOR_NAME,BK.CATEGORY
ORDER BY AU.AUTHOR_ID ASC,BK.CATEGORY DESC;