# -- 코드를 입력하세요
# SELECT CA.CAR_ID,CA.CAR_TYPE, ROUND(((CA.DAILY_FEE)*30)/100*(100-DI.DISCOUNT_RATE),0) FEE,HIS.START_DATE,HIS.END_DATE
# FROM CAR_RENTAL_COMPANY_CAR CA LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS ON CA.CAR_ID=HIS.CAR_ID
# LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DI ON CA.CAR_TYPE=DI.CAR_TYPE
# WHERE NOT(END_DATE >"2022-11-01" AND START_DATE <"2022-12-01")
# AND DI.DURATION_TYPE LIKE "30일%"
# GROUP BY CA.CAR_ID 
# HAVING CA.CAR_TYPE IN ("세단","SUV") and FEE>=500000 and FEE<=2000000
# ORDER BY FEE DESC, CA.CAR_TYPE ASC, CA.CAR_ID DESC;

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID=H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE=P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND P.DURATION_TYPE='30일 이상'
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV') AND (FEE>=500000 AND FEE<2000000) 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC