-- 코드를 입력하세요
SELECT I.REST_ID,I.REST_NAME,I.FOOD_TYPE,I.FAVORITES,I.ADDRESS,(SELECT ROUND(AVG(REVIEW_SCORE),2) FROM REST_REVIEW WHERE REST_ID=I.REST_ID) AS SCORE
FROM REST_INFO AS I
WHERE I.ADDRESS LIKE "서울%" AND (SELECT ROUND(AVG(REVIEW_SCORE),2) FROM REST_REVIEW WHERE REST_ID=I.REST_ID)>=0
ORDER BY SCORE desc,I.FAVORITES desc