-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) YEAR,MONTH(SALES_DATE) MONTH,US.GENDER, COUNT(DISTINCT US.USER_ID) USERS
FROM ONLINE_SALE SA LEFT JOIN USER_INFO US ON SA.USER_ID=US.USER_ID
WHERE US.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE) ,US.GENDER
ORDER BY YEAR(SALES_DATE),MONTH(SALES_DATE),US.GENDER;
# SELECT *
# FROM ONLINE_SALE SA LEFT JOIN USER_INFO US ON SA.USER_ID=US.USER_ID;