SELECT YEAR(SA.SALES_DATE),MONTH(SA.SALES_DATE),US.GENDER,COUNT(DISTINCT SA.USER_ID)
FROM USER_INFO US RIGHT JOIN ONLINE_SALE SA ON US.USER_ID=SA.USER_ID
WHERE US.GENDER IS NOT NULL
GROUP BY YEAR(SA.SALES_DATE),MONTH(SA.SALES_DATE),US.GENDER
ORDER BY YEAR(SA.SALES_DATE),MONTH(SA.SALES_DATE),US.GENDER;