-- 코드를 입력하세

WITH RECURSIVE CTE AS(

    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+   1 
    FROM CTE
    WHERE HOUR+1 <=23
    
)

SELECT HOUR,COUNT(DATETIME)
FROM CTE LEFT JOIN ANIMAL_OUTS AN ON CTE.HOUR=HOUR(AN.DATETIME)
GROUP BY HOUR