-- 코드를 작성해주세요

SELECT DISTINCT DEV.ID,DEV.EMAIL,DEV.FIRST_NAME,DEV.LAST_NAME
FROM DEVELOPERS DEV
LEFT JOIN SKILLCODES SKI
ON DEV.SKILL_CODE=DEV.SKILL_CODE|SKI.CODE
WHERE SKI.CATEGORY='Front End'
ORDER BY ID ASC